### ISSUE TITLE
Seg fault when points are too far outside coordinate field bounds

### ISSUE THREAD

**Issue by lafu9989** [jaseychanders/RRT#2]
When points are entered that are too far outside the scope of the coordinate field, the program segfaults. This isn't necessarily a big issue since the program will still run with points that are only slightly outside the coordinate field, and will not segfault (although it won't produce any meaningful output). Segfaults only started occurring on a coordinate field with side size 25 when I entered start and end points that were around ~100+ for x and y. 

Also, not an issue, but I just wanted to say that I thought this project was really interesting and very well done! Nice job :)

**Comment by jaseychanders** [comment]
Thanks for pointing this out!
